In [ ]:
# import os

# data_basic_path = '../year/'
# years = os.listdir(data_basic_path)
# files = []

##### Get floders CSV

In [5]:
import pandas as pd
import csv

In [6]:
import os

data_basic_path = '../year/'
years = os.listdir(data_basic_path)
full_path = []
dir =  "../merge"

In [7]:
for set_year in years:
    # - - - -  an year - - - - - 
    years_files = os.listdir(data_basic_path + '{}/'.format(set_year))
    for file in years_files:
        full_path.append(data_basic_path + set_year + '/' + file)

    merge_path_file = dir + "/{}_merge.csv".format(set_year)
    # 創建資料夾
    if not (os.path.exists(dir)):
        os.makedirs(dir)
        print("Dir Created ")
    else:
        print("Dir Existed ")

    # 創建 _merge.csv 並給予 主鍵('eRecordT01')
    with open(merge_path_file, 'w') as file:
        dw = csv.DictWriter(file, delimiter=',', fieldnames=['eRecordT01'])
        dw.writeheader()

    df_list = [pd.read_csv(file, low_memory=False) for file in full_path]

    for file in df_list:
        merge = pd.read_csv(merge_path_file, low_memory=False)
        result = merge.merge(file, on='eRecordT01', how='right')  #逐一基於eRecordT01欄位合併到第一個Pandas DataFrame
        result.to_csv(merge_path_file, index=False)

Dir Created
Dir Existed

C:\Users\User\AppData\Local\Temp\ipykernel_1660\2566896467.py:24: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROW_ID_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = merge.merge(file, on='eRecordT01', how='right')  #逐一基於eRecordT01欄位合併到第一個Pandas DataFrame
C:\Users\User\AppData\Local\Temp\ipykernel_1660\2566896467.py:24: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROW_ID_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = merge.merge(file, on='eRecordT01', how='right')  #逐一基於eRecordT01欄位合併到第一個Pandas DataFrame

Dir Existed

C:\Users\User\AppData\Local\Temp\ipykernel_1660\2566896467.py:24: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROW_ID_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = merge.merge(file, on='eRecordT01', how='right')  #逐一基於eRecordT01欄位合併到第一個Pandas DataFrame
C:\Users\User\AppData\Local\Temp\ipykernel_1660\2566896467.py:24: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROW_ID_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = merge.merge(file, on='eRecordT01', how='right')  #逐一基於eRecordT01欄位合併到第一個Pandas DataFrame
C:\Users\User\AppData\Local\Temp\ipykernel_1660\2566896467.py:24: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROW_ID_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = merge.merge(file, on='eRecordT01', how='right')  #逐一基於eRecordT01欄位合併到第一個Pandas DataFrame

KeyboardInterrupt:

##### Merge

##### Show DataFram

In [ ]:
merge_df = pd.read_csv('../merge/2011_merge.csv')
merge_df

C:\Users\User\AppData\Local\Temp\ipykernel_2352\3815289236.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  merge_df = pd.read_csv('../merge/2011_merge.csv')

,eRecordT01,eArrestT01,eArrestT02,eArrestT03,eArrestT04,eArrestT05,eArrestT06,eArrestT07,eArrestT08,eArrestT09,...,eVitalsT12,eVitalsT13,eVitalsT14,eVitalsT15,eVitalsT16,eVitalsT17,eVitalsT18,eVitalsT19,eVitalsT20,eVitalsT21
0,2011010110100410000334,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,91,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
1,2011010110100410000334,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,91,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
2,2011010110100410000334,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,91,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
3,2011010110100410000334,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,91,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
4,2011010110100410000334,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,91,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967651,2011123110100410916310,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,7701003,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
1967652,2011123110100410916310,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,7701003,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
1967653,2011123110100410916310,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,7701003,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
1967654,2011123110100410916310,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,7701003,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN
1967655,2011123110100410916310,111001.0,NaN,NaN,112001.0,113001.0,114001.0,115001.0,7701003.0,NaN,...,NaN,7701003,NaN,NaN,NaN,NaN,NaN,7701003,NaN,NaN

#####

In [ ]:
concat_path_file = dir + "/{}_concat.csv".format('10year')
res = pd.concat(df_list,axis=0, ignore_index=True)
res.to_csv(concat_path_file, index=False)
print(res)

                     eRecordT01  eArrestT01  eArrestT02  eArrestT03  \
0        2021010110100417526008    111001.0         NaN         NaN
1        2021010110100417526009    111001.0         NaN         NaN
2        2021010110100417526010    111001.0         NaN         NaN
3        2021010110100417526011    111001.0         NaN         NaN
4        2021010110100417526012    111001.0         NaN         NaN
...                         ...         ...         ...         ...
3212926  2021123110100495411001         NaN         NaN         NaN
3212927  2021123110100495524013         NaN         NaN         NaN
3212928  2021123110100495714007         NaN         NaN         NaN
3212929  2021123110100495806018         NaN         NaN         NaN
3212930  2021123110100495839014         NaN         NaN         NaN

         eArrestT04  eArrestT05  eArrestT06  eArrestT07  eArrestT08  \
0          112001.0    113001.0    114001.0    115001.0   7701003.0
1          112001.0    113001.0    114001.0    115001.0   7701003.0
2          112001.0    113001.0    114001.0    115001.0   7701003.0
3          112001.0    113001.0    114001.0    115001.0   7701003.0
4          112001.0    113001.0    114001.0    115001.0   7701003.0
...             ...         ...         ...         ...         ...
3212926         NaN         NaN         NaN         NaN         NaN
3212927         NaN         NaN         NaN         NaN         NaN
3212928         NaN         NaN         NaN         NaN         NaN
3212929         NaN         NaN         NaN         NaN         NaN
3212930         NaN         NaN         NaN         NaN         NaN

         eArrestT09  ...  eVitalsT12  eVitalsT13  eVitalsT14  eVitalsT15  \
0               NaN  ...         NaN         NaN         NaN         NaN
1               NaN  ...         NaN         NaN         NaN         NaN
2               NaN  ...         NaN         NaN         NaN         NaN
3               NaN  ...         NaN         NaN         NaN         NaN
4               NaN  ...         NaN         NaN         NaN         NaN
...             ...  ...         ...         ...         ...         ...
3212926         NaN  ...         NaN        96.0   7701001.0   7701001.0
3212927         NaN  ...         NaN        99.0   7701001.0   7701001.0
3212928         NaN  ...         NaN        97.0   7701001.0   7701001.0
3212929         NaN  ...         NaN        98.0   7701001.0   7701001.0
3212930         NaN  ...         NaN        99.0   7701001.0   7701001.0

         eVitalsT16 eVitalsT17  eVitalsT18  eVitalsT19  eVitalsT20  eVitalsT21
0               NaN        NaN         NaN         NaN         NaN         NaN
1               NaN        NaN         NaN         NaN         NaN         NaN
2               NaN        NaN         NaN         NaN         NaN         NaN
3               NaN        NaN         NaN         NaN         NaN         NaN
4               NaN        NaN         NaN         NaN         NaN         NaN
...             ...        ...         ...         ...         ...         ...
3212926         NaN  7701001.0         NaN        36.4         NaN   7701001.0
3212927         NaN  7701001.0         NaN        37.4         NaN   7701001.0
3212928         NaN  7701001.0         NaN        35.2         NaN   7701001.0
3212929         NaN  7701001.0         NaN   7701001.0         NaN   7701001.0
3212930         NaN  7701001.0         NaN        37.0         NaN   7701001.0

[3212931 rows x 125 columns]